apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline
rules:
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  - taskruns
  - pipelines
  - pipelineruns
  verbs:
  - get
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: pipeline
  apiGroup: rbac.authorization.k8s.io
