apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: budget-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-web
  template:
    metadata:
      labels:
        app: budget-web
    spec:
      containers:
      - name: web
        image: budget-app-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: RAILS_ENV
          value: development
