apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Akorede28/budget-app-manifests.git
    targetRevision: HEAD
    path: cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: budget-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
